theme: jekyll-theme-cayman
title: Multiscale modeling of the battle over iron in the lung
description: A multiscale computational model of the innate immune response to the opportunistic fungus Aspergillus fumigatus.
