theme: jekyll-theme-cayman
title: Multiscale modeling of the battle over iron in invasive lung infection
description: A multiscale computational model of the innate immune response to the opportunistic _Aspergillus fumigatus_ fungus.
